### ISSUE TITLE
关于数据库相关的问题

### ISSUE THREAD

**Issue by allmors** [AirCodeLabs/Hydrogen#3]
这个项目是必须依赖aircode云平台吗还是它是一个类似airecode云平台的开源？

数据库这块按照airecode文档执行的话
```
import aircode from 'aircode';

export default async function (params, context) {
  const dbs = aircode.db.table('persons');
  // Use `save` to add a new record
  const result = await dbs.save({
    name: 'Micheal',
    age: 28,
  });
  // const result = await dbs.where({ name: 'Micheal' }).find();

  return {
    result
  };
};
```
以上在hydroge中运行是访问api是没有任何信息的，数据是能正常在本地插入（如下图）
![image](https://github.com/AirCodeLabs/Hydrogen/assets/93471589/8787441f-5c43-4d3f-9668-bc323e208cec)
![image](https://github.com/AirCodeLabs/Hydrogen/assets/93471589/e37e9ba7-11a3-4f2b-b53e-fa9fb6f8b395)

**Comment by akira-cn** [comment]
> 这个项目是必须依赖aircode云平台吗还是它是一个类似airecode云平台的开源？
> 
> 数据库这块按照airecode文档执行的话
> 
> ```
> import aircode from 'aircode';
> 
> export default async function (params, context) {
>   const dbs = aircode.db.table('persons');
>   // Use `save` to add a new record
>   const result = await dbs.save({
>     name: 'Micheal',
>     age: 28,
>   });
>   // const result = await dbs.where({ name: 'Micheal' }).find();
> 
>   return {
>     result
>   };
> };
> ```
> 
> 以上在hydroge中运行是访问api是没有任何信息的，数据是能正常在本地插入（如下图） ![image](https://user-images.githubusercontent.com/93471589/261191386-8787441f-5c43-4d3f-9668-bc323e208cec.png) ![image](https://user-images.githubusercontent.com/93471589/261191554-e37e9ba7-11a3-4f2b-b53e-fa9fb6f8b395.png)

hydrogen 可以运行在本地或者其他平台，也可以集成到 aircode，bug 已解决，感谢反馈。
